"""
this file aims to provide a unified format converter for video generation and evaluation
"""
import os
import json 
def load_json(file_path):
    with open(file_path, 'r') as file:
        return json.load(file)

def save_json(data, file_path):
    with open(file_path, 'w') as file:
        json.dump(data, file, indent=4)
    
def load_prompts(prompt_file):
    with open(prompt_file, 'r', encoding='utf-8') as json_file:
        prompt_json = json.load(json_file)['prompts'] 
        ## 0622 modification : add filename_list, support dict and list 
        
        if isinstance(prompt_json, dict):#{k1:v1,k2:v2,...}
            filename_list = list(prompt_json.keys())
            filename_list = sorted([f[:-4] for f in filename_list])# 000001-010000
            prompt_list = list(prompt_json.values())
            print(filename_list)
        elif isinstance(prompt_json, list):#[{k:v},{k:v},...]
            ## notice: vbench requires .mp4 as ending but filename in savevideo does not
            filename_list = []
            prompt_list = []
            for item in prompt_json:
                for k,v in item.items():
                    filename_list.append(k[:-4])
                    prompt_list.append(v)
        else:
            print('failed file format in evaluation/funcs/load_prompts')
            exit()
def prompt_format_converter_txt2stdvbench(txtpath,jsonpath,n_sample=1):
    with open(txtpath,'r') as f:
        lines = f.readlines()
    captions = [i.strip() for i in lines]
    promptdict = {}
    for idx in range(n_sample):
        for _, prompt in enumerate(captions):
            # for videocrafter result 04:d (attention to mmodify this )
            videopath = f"{prompt.strip()}-{str(idx)}.mp4"
            promptdict[videopath] = prompt
    with open(jsonpath, "w") as f:
        json.dump(promptdict, f)
  
def prompt_format_converter_vc2vbench(txtpath,jsonpath,vbench_clip=True):
    """_summary_
    notice: the original txt only have prompts , so the filename is generated by index
    Args:
        txtpath (filename): videocrafter text prompt file path
        jsonpath (filename): vbench json of dict {videoname:prompt}
        vbench_clip (bool, optional): if trucate for clip 77 tokens for vbench. Defaults to True.
    """
    with open(txtpath,'r') as f:
        lines = f.readlines()
    captions = [i.strip() for i in lines ]
    promptdict = {}
    for idx, prompt in enumerate(captions):
        # for videocrafter result 04:d (attention to mmodify this )
        videopath = f"{idx:06d}.mp4"
        if vbench_clip:
            promptdict[videopath] = prompt[:77]
        else:
            promptdict[videopath] = prompt
    with open(jsonpath, "w") as f:
        json.dump(promptdict, f)
