model:
  base_learning_rate: 6.0e-06 # 1.5e-04
  scale_lr: False
  # empty_params_only: True # disable this means finetuning all parameters
  sd_checkpoint: /home/haoyu/research/shared_ckpts/StableDiffusion/v2-1_512-ema-pruned.ckpt
  ref_model_checkpoint: /home/haoyu/research/shared_ckpts/StableDiffusion/v2-1_512-ema-pruned.ckpt
  # pretrained_checkpoint:  /home/haoyu/research/shared_ckpts/VideoCrafter/VideoCrafter2-Text2Video-512/model.ckpt
  target: lvdm.models.ddpm3d.LatentDiffusion
  params:
    loss_type: dpo
    log_every_t: 200
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    timesteps: 1000
    first_stage_key: video
    cond_stage_key: caption
    cond_stage_trainable: false
    conditioning_key: crossattn
    image_size:
    - 40
    - 64
    channels: 4
    scale_by_std: false
    scale_factor: 0.18215
    use_ema: false
    uncond_type: empty_seq
    monitor: val/loss_simple_ema
    encoder_type: 2d
    use_scale: true
    scale_b: 0.7 # adapt to videocrafter-v2
    beta_dpo: 5000. # adapt to diffusion dpo 
    unet_config:
      target: lvdm.modules.networks.openaimodel3d.UNetModel
      params:
        freeze: True
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_head_channels: 64
        transformer_depth: 1
        context_dim: 1024
        use_linear: true
        use_checkpoint: true
        temporal_conv: true # adapt to videocrafter-v2
        temporal_attention: true
        temporal_selfatt_only: true
        use_relative_position: false # adapt to videocrafter-v2
        use_causal_attention: false
        temporal_length: 16
        addition_attention: true
        fps_cond: true # adapt to videocrafter-v2
    first_stage_config:
      target: lvdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: lvdm.modules.encoders.condition. 
      params:
        freeze: False
        layer: penultimate

data:
  target: data.lightning_data.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 16
    wrap: false
    train:
      target: data.picapic.PicAPic
      params:
        data_root: configs/data/picapic/train_data.yaml
        resolution: 512
        subset_split: train
        dreamlike_pairs_only: false
        random_crop: true
        no_hflip: true
        max_train_samples: 100,
        seed: None,
    validation:
      target: data.picapic.PicAPic
      params:
        data_root: configs/data/picapic/val_data.yaml
        resolution: 512
        subset_split: val
        dreamlike_pairs_only: false
        random_crop: false
        no_hflip: false
        max_train_samples: 100,
        seed: None,
lightning:
  callbacks:
    image_logger:
      target: utils.callbacks.ImageLogger
      params:
        batch_frequency:  1
        max_images: 6
        log_images_kwargs:
          unconditional_guidance_scale: 12 # need this, otherwise it is grey
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: "{epoch:06}-{step:09}"
        save_weights_only: False
        every_n_epochs: 300
        every_n_train_steps: null
  trainer:
    benchmark: True
    batch_size: 1
    num_workers: 1
    num_nodes: 1
    accumulate_grad_batches: 2
    max_epochs: 2000
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      every_n_epochs: 1
      filename: "{epoch:04}-{step:06}"