data:
  params:
    batch_size: 1
    num_workers: 16
    train:
      params:
        data_root: /home/rliuay/haoyu/research/DPO-videocrafter/configs/train/driver/train_configs/total_score_0P_pair23_vbscore/train_data.yaml
        resolution:
        - 320
        - 512
        subset_split: all
        video_length: 16
      target: data.macvid.MaCVidDPO
    validation:
      params:
        data_root: configs/data/vidpro/val_data.yaml
        resolution:
        - 320
        - 512
        subset_split: all
        video_length: 16
      target: data.macvid.MaCVidDPO
    wrap: false
  target: data.lightning_data.DataModuleFromConfig
lightning:
  callbacks:
    image_logger:
      params:
        batch_frequency: 100000
        log_images_kwargs:
          unconditional_guidance_scale: 12
        max_images: 2
        save_dir: log_image
        to_local: true
      target: utils.callbacks.ImageLogger
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_epochs: null
        every_n_train_steps: 991
        filename: step-{step:04}
        save_weights_only: true
      target: pytorch_lightning.callbacks.ModelCheckpoint
  modelcheckpoint:
    params:
      every_n_epochs: 1
      filename: '{epoch:04}-{step:06}'
    target: pytorch_lightning.callbacks.ModelCheckpoint
  trainer:
    accumulate_grad_batches: 2
    benchmark: true
    max_epochs: 3
    num_nodes: 1
    num_workers: 10
model:
  base_learning_rate: 6.0e-06
  params:
    channels: 4
    cond_stage_config:
      params:
        freeze: true
        layer: penultimate
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
    cond_stage_key: caption
    cond_stage_trainable: false
    conditioning_key: crossattn
    encoder_type: 2d
    first_stage_config:
      params:
        ddconfig:
          attn_resolutions: []
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          double_z: true
          dropout: 0.0
          in_channels: 3
          num_res_blocks: 2
          out_ch: 3
          resolution: 512
          z_channels: 4
        embed_dim: 4
        lossconfig:
          target: torch.nn.Identity
        monitor: val/rec_loss
      target: lvdm.models.autoencoder.AutoencoderKL
    first_stage_key: video
    image_size:
    - 40
    - 64
    linear_end: 0.012
    linear_start: 0.00085
    log_every_t: 200
    loss_type: dpo
    monitor: val/loss_simple_ema
    num_timesteps_cond: 1
    scale_b: 0.7
    scale_by_std: false
    scale_factor: 0.18215
    timesteps: 1000
    uncond_type: empty_seq
    unet_config:
      params:
        addition_attention: true
        attention_resolutions:
        - 4
        - 2
        - 1
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        context_dim: 1024
        fps_cond: true
        in_channels: 4
        model_channels: 320
        num_head_channels: 64
        num_res_blocks: 2
        out_channels: 4
        temporal_attention: true
        temporal_conv: true
        temporal_length: 16
        temporal_selfatt_only: true
        transformer_depth: 1
        use_causal_attention: false
        use_checkpoint: true
        use_linear: true
        use_relative_position: false
      target: lvdm.modules.networks.openaimodel3d.UNetModel
    use_ema: false
    use_scale: true
  pretrained_checkpoint: /home/rliuay/runtao/haoyu_data/init_ckpt/VideoCrafter2-Text2Video-512/model.ckpt
  ref_model_checkpoint: /home/rliuay/runtao/haoyu_data/init_ckpt/VideoCrafter2-Text2Video-512/ref_model.ckpt
  scale_lr: false
  target: lvdm.models.ddpm3d.LatentDiffusion
